### ISSUE TITLE
Compilation instructions under Chromium OS somewhat unclear

### ISSUE THREAD

**Issue by aegis2501** [google/hammer-kit#3]
In the readme it says that you should make a directory under the src directory of the Chrome OS source tree after checking it out and that you should "place the contents of this package there" (if one were to follow the linked Developer's Guide, this would be ~/chromiumos/src?) . After setting the correct board and building all other packages, then running the provided command  "in the directory where this package is kept" (outside of chroot) does not appear to add the packages to the build image. Have I missed something?

**Comment by sqazi** [comment]
It will produce the binaries in that directory, utilizing the chroot to do so.  It does not generate a package.  You will have to manually copy the binaries onto a Chromebook that is in developer mode.   Apologies for the unclear instructions.

**Comment by aegis2501** [comment]
I see. Thank you for the clarification :)
